"""add file.folder_id

Revision ID: 0430f16995b9
Revises: 89e1830799c6
Create Date: 2024-08-06 18:10:49.832726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0430f16995b9'
down_revision: Union[str, None] = '89e1830799c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('folder_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'file', 'folder', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'folder_id')
    # ### end Alembic commands ###
