"""delete nulladbe false

Revision ID: 14016d448b40
Revises: cfb5edfa2877
Create Date: 2024-08-06 18:55:23.272091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14016d448b40'
down_revision: Union[str, None] = 'cfb5edfa2877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'folder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('public_file', 'folder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('public_file', 'folder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('file', 'folder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
