"""add filename

Revision ID: 1613e4a30731
Revises: 6e0eb0a0198d
Create Date: 2024-07-23 17:42:57.113967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1613e4a30731'
down_revision: Union[str, None] = '6e0eb0a0198d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'filename')
    # ### end Alembic commands ###
