"""fix stats.public_file

Revision ID: 451a6c9c4fab
Revises: 63a6bf35fd5d
Create Date: 2024-08-08 20:07:13.702129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451a6c9c4fab'
down_revision: Union[str, None] = '63a6bf35fd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_stats_file_id_fkey', 'file_stats', type_='foreignkey')
    op.create_foreign_key(None, 'file_stats', 'public_file', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_stats', type_='foreignkey')
    op.create_foreign_key('file_stats_file_id_fkey', 'file_stats', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###
