"""add subscription

Revision ID: 4a3aad163655
Revises: cc02d3ddb1a2
Create Date: 2024-08-10 15:00:31.216708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3aad163655'
down_revision: Union[str, None] = 'cc02d3ddb1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('disk_space', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('subscription_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'subscription', ['subscription_id'], ['id'])
    op.drop_column('user', 'is_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'subscription_id')
    op.drop_table('subscription')
    # ### end Alembic commands ###
