"""add cascade delete stats in right place

Revision ID: 63a6bf35fd5d
Revises: af2511392be1
Create Date: 2024-08-08 19:57:51.572648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a6bf35fd5d'
down_revision: Union[str, None] = 'af2511392be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
