"""add paid users

Revision ID: cc02d3ddb1a2
Revises: 24cdf969923e
Create Date: 2024-08-09 21:02:42.738434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc02d3ddb1a2'
down_revision: Union[str, None] = '24cdf969923e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('total_uploaded_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_uploaded_size')
    op.drop_column('user', 'is_paid')
    # ### end Alembic commands ###
