"""add default in subscription_id

Revision ID: ede8cce35e9d
Revises: ee2c0b42b249
Create Date: 2024-08-10 15:51:15.129882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede8cce35e9d'
down_revision: Union[str, None] = 'ee2c0b42b249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
